#ifndef FACTOR_V3_FORMAL_NATIVE_BROKER_MANIFEST_H
#define FACTOR_V3_FORMAL_NATIVE_BROKER_MANIFEST_H

#define F3_BROKER_RUNTIME_PATH L""
#define F3_BROKER_RUNTIME_SHA256 L""
#define F3_BROKER_SOURCE_PATH L""
#define F3_BROKER_SOURCE_SHA256 L""
#define F3_BROKER_CREDENTIAL_SLOT_PATH L""
#define F3_BROKER_CNG_PROVIDER L"Microsoft Software Key Storage Provider"
#define F3_BROKER_CNG_KEY_NAME L"quant-signal-lkj-factor-v3-formal"
#define F3_BROKER_CNG_ALGORITHM NCRYPT_RSA_ALGORITHM
#define F3_BROKER_SERVICE_NAME L"QuantSignalLkjFactorV3FormalBroker"
#define F3_BROKER_SERVICE_SID L""
#define F3_BROKER_WORKER_SID L""
#define F3_BROKER_EXECUTION_PUBLIC_MODULUS_HEX ""
#define F3_BROKER_EXECUTION_PUBLIC_EXPONENT 0u
#define F3_BROKER_PRODUCTION_HANDOFF_READY 0

#endif
