#ifndef FACTOR_V3_FORMAL_NATIVE_BROKER_MANIFEST_H
#define FACTOR_V3_FORMAL_NATIVE_BROKER_MANIFEST_H

#define F3_BROKER_RUNTIME_PATH L""
#define F3_BROKER_RUNTIME_SHA256 L""
#define F3_BROKER_SOURCE_PATH L""
#define F3_BROKER_SOURCE_SHA256 L""
#define F3_BROKER_SIGNING_KEY_SLOT_PATH L""
#define F3_BROKER_CREDENTIAL_SLOT_PATH L""
#define F3_BROKER_PRODUCTION_HANDOFF_READY 0

#endif
